import { NormalJob } from "../github-workflow";
export type Step = Required<NormalJob>["steps"][0];
export interface checkoutArgs {
    repo?: string;
    path?: string;
    fetchDepth?: number;
}
export declare function CheckoutRepoStep(args?: checkoutArgs): Step;
export declare function CheckoutRepoStepAtPR(): Step;
export declare function CheckoutScriptsRepoStep(): Step;
export declare function CheckoutTagsStep(): Step;
export declare function GoogleAuth(requiresGcp?: boolean): Step;
export declare function SetupGCloud(requiresGcp?: boolean): Step;
export declare function ConfigureAwsCredentialsForTests(requiresAws?: boolean): Step;
export declare function ConfigureAwsCredentialsForPublish(): Step;
export declare function ConfigureAwsCredentialsForCoverageDataUpload(): Step;
export declare function InstallGo(version?: string): Step;
export declare function InstallNodeJS(version?: string): Step;
export declare function InstallDotNet(version?: string): Step;
export declare function InstallJava(version?: string): Step;
export declare function InstallPython(version?: string): Step;
export declare function InstallPlugins(): Step;
export declare function InstallPythonDeps(): Step;
export declare function InstallSDKDeps(): Step;
export declare function InstallPulumiCtl(): Step;
export declare function InstallSchemaChecker(): Step;
export declare function DispatchDocsBuildEvent(): Step;
export declare function InstallPulumiCli(version?: string): Step;
export declare function PrintPulumiCliVersion(): Step;
export declare function RunDockerComposeStep(required?: boolean): Step;
export declare function RunSetUpScriptStep(setupScript?: string): Step;
export declare function BuildBinariesStep(): Step;
export declare function BuildSdksStep(): Step;
export declare function UploadProviderBinariesStep(): Step;
export declare function UploadSdkStep(): Step;
export declare function DownloadProviderStep(): Step;
export declare function DownloadSDKsStep(): Step;
export declare function DownloadSpecificSDKStep(name: string): Step;
export declare function UnzipProviderBinariesStep(): Step;
export declare function UnzipSDKsStep(): Step;
export declare function UnzipSpecificSDKStep(name: string): Step;
export declare function ZipProviderBinariesStep(): Step;
export declare function ZipSDKsStep(): Step;
export declare function NotifySlack(name: string): Step;
export declare function CheckCleanWorkTreeStep(): Step;
export declare function SetNugetSource(): Step;
export declare function SetProvidersToPATH(): Step;
export declare function SetPackageVersionToEnv(): Step;
export declare function RunTests(): Step;
export declare function SetPreReleaseVersion(): Step;
export declare function RunGoReleaserWithArgs(args?: string): Step;
export declare function RunCommand(command: string): Step;
export declare function RunPublishSDK(): Step;
export declare function RunPublishJavaSDK(): Step;
export declare function TagSDKTag(): Step;
export declare function UpdatePulumiTerraformBridgeDependency(): Step;
export declare function CommitChanges(refName: string): Step;
export declare function PullRequest(refName: string, prTitle: string, user: string): Step;
export declare function CheckSchemaChanges(): Step;
export declare function CommentSchemaChangesOnPR(): Step;
export declare function CommandDispatchStep(providerName: string): Step;
export declare function CreateCommentsUrlStep(): Step;
export declare function EchoSuccessStep(): Step;
export declare function UpdatePRWithResultsStep(): Step;
export declare function CommentPRWithSlashCommandStep(command?: string): Step;
export declare function EchoCoverageOutputDirStep(): Step;
export declare function GenerateCoverageDataStep(): Step;
export declare function PrintCoverageDataStep(): Step;
export declare function UploadCoverageDataStep(): Step;
export declare function SetupGotestfmt(): Step;
export declare function SchemaFileChanged(): Step;
export declare function SdkFilesChanged(): Step;
export declare function SendCodegenWarnCommentPr(): Step;
//# sourceMappingURL=steps.d.ts.map